### ISSUE TITLE
Error  linking uWSGI during build   

### ISSUE THREAD

**Issue by AFosch** [ajnisbet/opentopodata#97]
Hello, 
I am trying to run Open Topo Data with Docker (26.0.0) on a Linux server (Ubuntu 20.04). I have followed the commands on the documentation and there is an error during the make build command. 
```
git clone https://github.com/ajnisbet/opentopodata.git 
cd opentopodata 
make build 
```
Did anyone experience a similar problem? 

The error seems to be related to linking the "uWSGI" package. Here you can find the error message: 
```
[+] Building 8.5s (8/14)                                                                                                                        docker:default
 => [internal] load build definition from Dockerfile                                                                                                      0.0s
 => => transferring dockerfile: 1.57kB                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:3.11.8-slim-bookworm                                                                            0.7s
 => [internal] load .dockerignore                                                                                                                         0.0s
 => => transferring context: 113B                                                                                                                         0.0s
 => [builder 1/3] FROM docker.io/library/python:3.11.8-slim-bookworm@sha256:90f8795536170fd08236d2ceb74fe7065dbf74f738d8b84bfbf263656654dc9b              0.0s
 => [internal] load build context                                                                                                                         0.0s
 => => transferring context: 5.82kB                                                                                                                       0.0s
 => CACHED [builder 2/3] RUN set -e &&     apt-get update &&     apt-get install -y --no-install-recommends         gcc         python3.11-dev            0.0s
 => CACHED [stage-1 2/8] RUN set -e &&     apt-get update &&     apt-get install -y --no-install-recommends         nginx         memcached         supe  0.0s
 => ERROR [builder 3/3] RUN pip config set global.disable-pip-version-check true &&     pip wheel --wheel-dir=/root/wheels uwsgi==2.0.24 &&     pip whee  7.8s
------                                                                                                                                                         
 > [builder 3/3] RUN pip config set global.disable-pip-version-check true &&     pip wheel --wheel-dir=/root/wheels uwsgi==2.0.24 &&     pip wheel --wheel-dir=/root/wheels regex==2023.12.25:                                                                                                                                
1.921 Writing to /root/.config/pip/pip.conf                                                                                                                    
2.824 Collecting uwsgi==2.0.24                                                                                                                                 
2.893   Downloading uwsgi-2.0.24.tar.gz (810 kB)                                                                                                               
2.921      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 810.6/810.6 kB 34.8 MB/s eta 0:00:00
3.072   Preparing metadata (setup.py): started
3.909   Preparing metadata (setup.py): finished with status 'done'
3.913 Building wheels for collected packages: uwsgi
3.914   Building wheel for uwsgi (setup.py): started
7.212   Building wheel for uwsgi (setup.py): finished with status 'error'
7.257   error: subprocess-exited-with-error
7.257   
7.257   × python setup.py bdist_wheel did not run successfully.
7.257   │ exit code: 1
7.257   ╰─> [201 lines of output]
7.257       /usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py:264: UserWarning: Unknown distribution option: 'descriptions'
7.257         warnings.warn(msg)
7.257       running bdist_wheel
7.257       running build
7.257       running build_py
7.257       creating build
7.257       creating build/lib
7.257       copying uwsgidecorators.py -> build/lib
7.257       /usr/local/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
7.257         warnings.warn(
7.257       installing to build/bdist.linux-x86_64/wheel
7.257       running install
7.257       using profile: buildconf/default.ini
7.257       detected include path: ['/usr/lib/gcc/x86_64-linux-gnu/12/include', '/usr/local/include', '/usr/include/x86_64-linux-gnu', '/usr/include']
7.257       Patching "bin_name" to properly install_scripts dir
7.257       detected CPU cores: 48
7.257       configured CFLAGS: -O2 -I. -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wformat-signedness -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -DUWSGI_HAS_IFADDRS -DUWSGI_ZLIB -DUWSGI_LOCK_USE_MUTEX -DUWSGI_EVENT_USE_EPOLL -DUWSGI_EVENT_TIMER_USE_TIMERFD -DUWSGI_EVENT_FILEMONITOR_USE_INOTIFY -DUWSGI_VERSION="\"2.0.24\"" -DUWSGI_VERSION_BASE="2" -DUWSGI_VERSION_MAJOR="0" -DUWSGI_VERSION_MINOR="24" -DUWSGI_VERSION_REVISION="0" -DUWSGI_VERSION_CUSTOM="\"\"" -DUWSGI_YAML -DUWSGI_XML -DUWSGI_XML_EXPAT -DUWSGI_PLUGIN_DIR="\".\"" -DUWSGI_DECLARE_EMBEDDED_PLUGINS="UDEP(python);UDEP(gevent);UDEP(ping);UDEP(cache);UDEP(nagios);UDEP(rrdtool);UDEP(carbon);UDEP(rpc);UDEP(corerouter);UDEP(fastrouter);UDEP(http);UDEP(ugreen);UDEP(signal);UDEP(syslog);UDEP(rsyslog);UDEP(logsocket);UDEP(router_uwsgi);UDEP(router_redirect);UDEP(router_basicauth);UDEP(zergpool);UDEP(redislog);UDEP(mongodblog);UDEP(router_rewrite);UDEP(router_http);UDEP(logfile);UDEP(router_cache);UDEP(rawrouter);UDEP(router_static);UDEP(sslrouter);UDEP(spooler);UDEP(cheaper_busyness);UDEP(symcall);UDEP(transformation_tofile);UDEP(transformation_gzip);UDEP(transformation_chunked);UDEP(transformation_offload);UDEP(router_memcached);UDEP(router_redis);UDEP(router_hash);UDEP(router_expires);UDEP(router_metrics);UDEP(transformation_template);UDEP(stats_pusher_socket);" -DUWSGI_LOAD_EMBEDDED_PLUGINS="ULEP(python);ULEP(gevent);ULEP(ping);ULEP(cache);ULEP(nagios);ULEP(rrdtool);ULEP(carbon);ULEP(rpc);ULEP(corerouter);ULEP(fastrouter);ULEP(http);ULEP(ugreen);ULEP(signal);ULEP(syslog);ULEP(rsyslog);ULEP(logsocket);ULEP(router_uwsgi);ULEP(router_redirect);ULEP(router_basicauth);ULEP(zergpool);ULEP(redislog);ULEP(mongodblog);ULEP(router_rewrite);ULEP(router_http);ULEP(logfile);ULEP(router_cache);ULEP(rawrouter);ULEP(router_static);ULEP(sslrouter);ULEP(spooler);ULEP(cheaper_busyness);ULEP(symcall);ULEP(transformation_tofile);ULEP(transformation_gzip);ULEP(transformation_chunked);ULEP(transformation_offload);ULEP(router_memcached);ULEP(router_redis);ULEP(router_hash);ULEP(router_expires);ULEP(router_metrics);ULEP(transformation_template);ULEP(stats_pusher_socket);"
7.257       *** uWSGI compiling server core ***
7.257       [thread 1][gcc] core/utils.o
7.257       [thread 2][gcc] core/protocol.o
7.257       [thread 3][gcc] core/socket.o
7.257       [thread 4][gcc] core/logging.o
7.257       [thread 5][gcc] core/master.o
7.257       [thread 6][gcc] core/master_utils.o
7.257       [thread 8][gcc] core/emperor.o
7.257       [thread 7][gcc] core/notify.o
7.257       [thread 9][gcc] core/mule.o
7.257       [thread 11][gcc] core/subscription.o
7.257       [thread 10][gcc] core/stats.o
7.257       [thread 12][gcc] core/sendfile.o
7.257       [thread 13][gcc] core/async.o
7.257       [thread 15][gcc] core/master_checks.o
7.257       [thread 14][gcc] core/fifo.o
7.257       [thread 17][gcc] core/offload.o
7.257       [thread 16][gcc] core/io.o
7.257       [thread 18][gcc] core/static.o
7.257       [thread 19][gcc] core/websockets.o
7.257       [thread 20][gcc] core/spooler.o
7.257       [thread 21][gcc] core/snmp.o
7.257       [thread 22][gcc] core/exceptions.o
7.257       [thread 25][gcc] core/config.o
7.257       [thread 26][gcc] core/setup_utils.o
7.257       [thread 24][gcc] core/clock.o
7.257       [thread 23][gcc] core/init.o
7.257       [thread 27][gcc] core/buffer.o
7.257       [thread 29][gcc] core/reader.o
7.257       [thread 30][gcc] core/writer.o
7.257       [thread 28][gcc] core/alarm.o
7.257       [thread 31][gcc] core/cron.o
7.257       [thread 32][gcc] core/hooks.o
7.257       [thread 33][gcc] core/plugins.o
7.257       [thread 34][gcc] core/lock.o
7.257       [thread 35][gcc] core/cache.o
7.257       [thread 36][gcc] core/daemons.o
7.257       [thread 37][gcc] core/errors.o
7.257       [thread 38][gcc] core/hash.o
7.257       [thread 39][gcc] core/master_events.o
7.257       [thread 41][gcc] core/chunked.o
7.257       [thread 42][gcc] core/queue.o
7.257       [thread 43][gcc] core/event.o
7.257       [thread 40][gcc] core/signal.o
7.257       [thread 44][gcc] core/strings.o
7.257       [thread 45][gcc] core/progress.o
7.257       [thread 46][gcc] core/timebomb.o
7.257       Exception in thread Thread-21 (thread_compiler):
7.257       [thread 47][gcc] core/ini.oTraceback (most recent call last):
7.257       
7.257         File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
7.257       [thread 0][gcc] core/fsmon.o
7.257           self.run()
7.257         File "/usr/local/lib/python3.11/threading.py", line 982, in run
7.257           self._target(*self._args, **self._kwargs)
7.257         File "/tmp/pip-wheel-6ikgdvxr/uwsgi_ca3e2521bc314eaa9b2ca800132aec14/uwsgiconfig.py", line 116, in thread_compiler
7.257           ret = subprocess.call(cmdline, shell=True)
7.257                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
7.257         File "/usr/local/lib/python3.11/subprocess.py", line 389, in call
7.257           with Popen(*popenargs, **kwargs) as p:
7.257                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
7.257         File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
7.257           self._execute_child(args, executable, preexec_fn, close_fds,
7.257         File "/usr/local/lib/python3.11/subprocess.py", line 1953, in _execute_child
7.257           raise child_exception_type(errno_num, err_msg, err_filename)
7.257       OSError: [Errno 14] Bad address: '/bin/sh'
7.257       [thread 46][gcc] core/mount.o
7.257       [thread 26][gcc] core/metrics.o
7.257       [thread 7][gcc] core/plugins_builder.o
7.257       [thread 24][gcc] core/sharedarea.o
7.257       [thread 12][gcc] core/rpc.o
7.257       [thread 45][gcc] core/gateway.o
7.257       [thread 41][gcc] core/loop.o
7.257       [thread 42][gcc] core/cookie.o
7.257       [thread 14][gcc] core/querystring.o
7.257       [thread 0][gcc] core/rb_timers.o
7.257       [thread 47][gcc] core/transformations.o
7.257       [thread 39][gcc] core/uwsgi.o
7.257       [thread 23][gcc] proto/base.o
7.257       [thread 34][gcc] proto/uwsgi.o
7.257       [thread 28][gcc] proto/http.o
7.257       [thread 38][gcc] proto/fastcgi.o
7.257       [thread 15][gcc] proto/scgi.o
7.257       [thread 46][gcc] proto/puwsgi.o
7.257       [thread 19][gcc] lib/linux_ns.o
7.257       [thread 31][gcc] core/zlib.o
7.257       [thread 9][gcc] core/yaml.o
7.257       [thread 36][gcc] core/xmlconf.o
7.257       [thread 7][gcc] core/dot_h.o
7.257       [thread 29][gcc] core/config_py.o
7.257       *** uWSGI compiling embedded plugins ***
7.257       [thread 22][gcc] plugins/python/python_plugin.o
7.257       [thread 27][gcc] plugins/python/pyutils.o
7.257       [thread 33][gcc] plugins/python/pyloader.o
7.257       [thread 37][gcc] plugins/python/wsgi_handlers.o
7.257       [thread 7][gcc] plugins/python/wsgi_headers.o
7.257       [thread 32][gcc] plugins/python/wsgi_subhandler.o
7.257       [thread 44][gcc] plugins/python/web3_subhandler.o
7.257       [thread 18][gcc] plugins/python/pump_subhandler.o
7.257       [thread 29][gcc] plugins/python/gil.o
7.257       [thread 25][gcc] plugins/python/uwsgi_pymodule.o
7.257       [thread 47][gcc] plugins/python/profiler.o
7.257       [thread 2][gcc] plugins/python/symimporter.o
7.257       [thread 17][gcc] plugins/python/tracebacker.o
7.257       [thread 21][gcc] plugins/python/raw.o
7.257       [thread 13][gcc] plugins/gevent/gevent.o
7.257       [thread 45][gcc] plugins/gevent/hooks.o
7.257       [thread 0][gcc] plugins/ping/ping_plugin.o
7.257       [thread 34][gcc] plugins/cache/cache.o
7.257       [thread 43][gcc] plugins/nagios/nagios.o
7.257       [thread 24][gcc] plugins/rrdtool/rrdtool.o
7.257       [thread 10][gcc] plugins/carbon/carbon.o
7.257       [thread 36][gcc] plugins/rpc/rpc_plugin.o
7.257       [thread 15][gcc] plugins/corerouter/cr_common.o
7.257       [thread 42][gcc] plugins/corerouter/cr_map.o
7.257       [thread 14][gcc] plugins/corerouter/corerouter.o
7.257       [thread 5][gcc] plugins/fastrouter/fastrouter.o
7.257       [thread 41][gcc] plugins/http/http.o
7.257       [thread 12][gcc] plugins/http/keepalive.o
7.257       [thread 23][gcc] plugins/http/https.o
7.257       [thread 19][gcc] plugins/http/spdy3.o
7.257       [thread 38][gcc] plugins/ugreen/ugreen.o
7.257       [thread 11][gcc] plugins/signal/signal_plugin.o
7.257       [thread 31][gcc] plugins/syslog/syslog_plugin.o
7.257       [thread 40][gcc] plugins/rsyslog/rsyslog_plugin.o
7.257       [thread 21][gcc] plugins/logsocket/logsocket_plugin.o
7.257       plugins/python/pyutils.c: In function ‘init_pyargv’:
7.257       plugins/python/pyutils.c:391:9: warning: ‘PySys_SetArgv’ is deprecated [-Wdeprecated-declarations]
7.257         391 |         PySys_SetArgv(up.argc, up.py_argv);
7.257             |         ^~~~~~~~~~~~~
7.257       In file included from /usr/local/include/python3.11/Python.h:96,
7.257                        from plugins/python/uwsgi_python.h:4,
7.257                        from plugins/python/pyutils.c:1:
7.257       /usr/local/include/python3.11/sysmodule.h:13:38: note: declared here
7.257          13 | Py_DEPRECATED(3.11) PyAPI_FUNC(void) PySys_SetArgv(int, wchar_t **);
7.257             |                                      ^~~~~~~~~~~~~
7.257       [thread 46][gcc] plugins/router_uwsgi/router_uwsgi.o
7.257       [thread 23][gcc] plugins/router_redirect/router_redirect.o
7.257       [thread 9][gcc] plugins/router_basicauth/router_basicauth.o
7.257       plugins/python/python_plugin.c: In function ‘uwsgi_python_init’:
7.257       plugins/python/python_plugin.c:254:17: warning: ‘Py_SetPythonHome’ is deprecated [-Wdeprecated-declarations]
7.257         254 |                 Py_SetPythonHome(wpyhome);
7.257             |                 ^~~~~~~~~~~~~~~~
7.257       In file included from /usr/local/include/python3.11/Python.h:94,
7.257                        from plugins/python/uwsgi_python.h:4,
7.257                        from plugins/python/python_plugin.c:1:
7.257       /usr/local/include/python3.11/pylifecycle.h:40:38: note: declared here
7.257          40 | Py_DEPRECATED(3.11) PyAPI_FUNC(void) Py_SetPythonHome(const wchar_t *);
7.257             |                                      ^~~~~~~~~~~~~~~~
7.257       plugins/python/python_plugin.c:278:9: warning: ‘Py_SetProgramName’ is deprecated [-Wdeprecated-declarations]
7.257         278 |         Py_SetProgramName(pname);
7.257             |         ^~~~~~~~~~~~~~~~~
7.257       /usr/local/include/python3.11/pylifecycle.h:37:38: note: declared here
7.257          37 | Py_DEPRECATED(3.11) PyAPI_FUNC(void) Py_SetProgramName(const wchar_t *);
7.257             |                                      ^~~~~~~~~~~~~~~~~
7.257       [thread 30][gcc] plugins/zergpool/zergpool.o
7.257       [thread 43][gcc] plugins/redislog/redislog_plugin.o
7.257       [thread 17][gcc] plugins/mongodblog/mongodblog_plugin.o
7.257       [thread 24][gcc] plugins/router_rewrite/router_rewrite.o
7.257       [thread 32][gcc] plugins/router_http/router_http.o
7.257       [thread 12][gcc] plugins/logfile/logfile.o
7.257       [thread 29][gcc] plugins/router_cache/router_cache.o
7.257       [thread 47][gcc] plugins/rawrouter/rawrouter.o
7.257       [thread 0][gcc] plugins/router_static/router_static.o
7.257       [thread 19][gcc] plugins/sslrouter/sslrouter.o
7.257       [thread 27][gcc] plugins/spooler/spooler_plugin.o
7.257       [thread 36][gcc] plugins/cheaper_busyness/cheaper_busyness.o
7.257       [thread 42][gcc] plugins/symcall/symcall_plugin.o
7.257       [thread 44][gcc] plugins/transformation_tofile/tofile.o
7.257       [thread 13][gcc] plugins/transformation_gzip/gzip.o
7.257       [thread 40][gcc] plugins/transformation_chunked/chunked.o
7.257       [thread 16][gcc] plugins/transformation_offload/offload.o
7.257       [thread 31][gcc] plugins/router_memcached/router_memcached.o
7.257       [thread 33][gcc] plugins/router_redis/router_redis.o
7.257       [thread 7][gcc] plugins/router_hash/router_hash.o
7.257       [thread 43][gcc] plugins/router_expires/expires.o
7.257       [thread 15][gcc] plugins/router_metrics/plugin.o
7.257       [thread 23][gcc] plugins/transformation_template/tt.o
7.257       [thread 21][gcc] plugins/stats_pusher_socket/plugin.o
7.257       *** uWSGI linking ***
7.257       gcc -o build/bdist.linux-x86_64/wheel/uWSGI-2.0.24.data/scripts/uwsgi -L/usr/local/lib -Wl,-rpath,/usr/local/lib core/utils.o core/protocol.o core/socket.o core/logging.o core/master.o core/master_utils.o core/emperor.o core/notify.o core/mule.o core/subscription.o core/stats.o core/sendfile.o core/async.o core/master_checks.o core/fifo.o core/offload.o core/io.o core/static.o core/websockets.o core/spooler.o core/snmp.o core/exceptions.o core/config.o core/setup_utils.o core/clock.o core/init.o core/buffer.o core/reader.o core/writer.o core/alarm.o core/cron.o core/hooks.o core/plugins.o core/lock.o core/cache.o core/daemons.o core/errors.o core/hash.o core/master_events.o core/chunked.o core/queue.o core/event.o core/signal.o core/strings.o core/progress.o core/timebomb.o core/ini.o core/fsmon.o core/mount.o core/metrics.o core/plugins_builder.o core/sharedarea.o core/rpc.o core/gateway.o core/loop.o core/cookie.o core/querystring.o core/rb_timers.o core/transformations.o core/uwsgi.o proto/base.o proto/uwsgi.o proto/http.o proto/fastcgi.o proto/scgi.o proto/puwsgi.o lib/linux_ns.o core/zlib.o core/yaml.o core/xmlconf.o core/dot_h.o core/config_py.o plugins/python/python_plugin.o plugins/python/pyutils.o plugins/python/pyloader.o plugins/python/wsgi_handlers.o plugins/python/wsgi_headers.o plugins/python/wsgi_subhandler.o plugins/python/web3_subhandler.o plugins/python/pump_subhandler.o plugins/python/gil.o plugins/python/uwsgi_pymodule.o plugins/python/profiler.o plugins/python/symimporter.o plugins/python/tracebacker.o plugins/python/raw.o plugins/gevent/gevent.o plugins/gevent/hooks.o plugins/ping/ping_plugin.o plugins/cache/cache.o plugins/nagios/nagios.o plugins/rrdtool/rrdtool.o plugins/carbon/carbon.o plugins/rpc/rpc_plugin.o plugins/corerouter/cr_common.o plugins/corerouter/cr_map.o plugins/corerouter/corerouter.o plugins/fastrouter/fastrouter.o plugins/http/http.o plugins/http/keepalive.o plugins/http/https.o plugins/http/spdy3.o plugins/ugreen/ugreen.o plugins/signal/signal_plugin.o plugins/syslog/syslog_plugin.o plugins/rsyslog/rsyslog_plugin.o plugins/logsocket/logsocket_plugin.o plugins/router_uwsgi/router_uwsgi.o plugins/router_redirect/router_redirect.o plugins/router_basicauth/router_basicauth.o plugins/zergpool/zergpool.o plugins/redislog/redislog_plugin.o plugins/mongodblog/mongodblog_plugin.o plugins/router_rewrite/router_rewrite.o plugins/router_http/router_http.o plugins/logfile/logfile.o plugins/router_cache/router_cache.o plugins/rawrouter/rawrouter.o plugins/router_static/router_static.o plugins/sslrouter/sslrouter.o plugins/spooler/spooler_plugin.o plugins/cheaper_busyness/cheaper_busyness.o plugins/symcall/symcall_plugin.o plugins/transformation_tofile/tofile.o plugins/transformation_gzip/gzip.o plugins/transformation_chunked/chunked.o plugins/transformation_offload/offload.o plugins/router_memcached/router_memcached.o plugins/router_redis/router_redis.o plugins/router_hash/router_hash.o plugins/router_expires/expires.o plugins/router_metrics/plugin.o plugins/transformation_template/tt.o plugins/stats_pusher_socket/plugin.o -lpthread -lm -rdynamic -ldl -lz -lexpat -ldl -lm -lpython3.11 -lcrypt
7.257       /usr/bin/ld: cannot find core/spooler.o: No such file or directory
7.257       collect2: error: ld returned 1 exit status
7.257       *** error linking uWSGI ***
7.257       [end of output]
7.257   
7.257   note: This error originates from a subprocess, and is likely not a problem with pip.
7.258   ERROR: Failed building wheel for uwsgi
7.258   Running setup.py clean for uwsgi
7.608 Failed to build uwsgi
7.608 ERROR: Failed to build one or more wheels
------
Dockerfile:9
--------------------
   8 |     
   9 | >>> RUN pip config set global.disable-pip-version-check true && \
  10 | >>>     pip wheel --wheel-dir=/root/wheels uwsgi==2.0.24 && \
  11 | >>>     pip wheel --wheel-dir=/root/wheels regex==2023.12.25
  12 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pip config set global.disable-pip-version-check true &&     pip wheel --wheel-dir=/root/wheels uwsgi==2.0.24 &&     pip wheel --wheel-dir=/root/wheels regex==2023.12.25" did not complete successfully: exit code: 1
make: *** [Makefile:5: build] Error 1
```

 Thanks in advance.

**Comment by ajnisbet** [comment]
Hmm, I just tried a build from scratch on a 20.04 machine and had no issues:

```
make build
  docker build --no-cache --tag opentopodata:`cat VERSION` --file docker/Dockerfile .
  [+] Building 33.8s (15/15) FINISHED   
                                                                                             
docker --version
    Docker version 25.0.3, build 4debf41
```

Some things to try:
* Add `--no-cache` to the `build` docker command in the Makefile
* You could also try `build-m1`: despite the name, this image should also work on linux.
* In `docker/Dockerfile` change `uwsgi==2.0.24` to `uwsgi==2.0.22`.
* I suspect upgrading first docker, then if that doesn't work running `apt upgrade` would fix the issue. But also that might impact other software you're running!

Let me know if you can get it resolved!

**Comment by AFosch** [comment]
Thanks for the reply.

In the end, I modified both the `docker/Dockerfile` to `uwsgi==2.0.22` and added the `--no-cache` flag on the `build` command of the `Makefile`.  These changes solved the issue. 

Thanks again!

**Comment by ajnisbet** [comment]
Interesting, good to know!

Let me know if there's anything else I can help with regarding opentopodata or elevation data!
